
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwymrkjjyauyridsepcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3eW1ya2pqeWF1eXJpZHNlcGNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTgwNjUsImV4cCI6MjA1OTUzNDA2NX0.C1t2mj8XMiWTac-BXP-mFqUBVMWNfFor8F35eDxkdfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
